 
# Don't use a specific environment we install everything ourselves.
language: generic

# Needed to install custom packages.
sudo: required

# What environments we want to build for.
matrix:
  include:
    #- env: GHCVER=7.10.2 CABALVER=1.22 ALEXVER=3.1.4 HAPPYVER=1.19.5
    #  addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    #- env: GHCVER=7.10.3 CABALVER=1.22 ALEXVER=3.1.4 HAPPYVER=1.19.5
    #  addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}

before_install:
  - unset CC
install:
  # Don't need to do manual installation, because "addons" does that for us.
  #- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  #- travis_retry sudo apt-get update
  #- travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER-dyn alex-$ALEXVER happy-$HAPPYVER
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
  - travis_retry cabal update

before_script:
  - cabal sandbox init
  # Setup the library dependency of the ebba-example.
  - git clone https://github.com/glutamate/gnewplot.git ./examples/arrow/ebba/gnewplot
  - cabal sandbox add-source ./examples/arrow/ebba/gnewplot

script:
  # Print version information
  - ghc   --version
  - cabal --version
  - alex  --version
  - happy --version
  # Build the supermonad library.
  # According to:
  # https://docs.travis-ci.com/user/ci-environment/#Overview
  # We can use 2 cores.
  - travis_retry cabal install -j2
  # Find the example directories that contain a cabal project and builds them in the current context.
  - find ./examples -type f -iname '*.cabal' -exec dirname {} \; | xargs -n1 cabal install -j2

notifications:
  email: true

branches:
  only:
    - master
    - dev
