 
# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: c
env:
  # - GHCVER=7.10.3
  - GHCVER=8.0.2

before_install:
  - unset CC
install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER-dyn alex-3.1.4 happy-1.19.5
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  - travis_retry cabal update

before_script:
  - cabal sandbox init
  # Setup the library dependency of the ebba-example.
  - git clone https://github.com/glutamate/gnewplot.git ./examples/arrow/ebba/gnewplot
  - cabal sandbox add-source ./examples/arrow/ebba/gnewplot

script:
  # Build the supermonad library.
  - travis_retry cabal install -v -j1
  # Find the example directories that contain a cabal project and builds them in the current context.
  - find ./examples -type f -iname '*.cabal' -exec dirname {} \; | xargs -n1 cabal install

notifications:
  email: true

branches:
  only:
    - master
    - dev
