 
# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: c
env:
  # - GHCVER=7.10.3
  - GHCVER=8.0.2

# Note: the distinction between `before_install` and `install` is not important.
before_install:
  - unset CC
install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER-dyn alex-3.1.4 happy-1.19.5
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  - travis_retry cabal update

script:
  - travis_retry cabal install -v -j1

notifications:
  email: true

branches:
  only:
    - master
    - dev
